### PR TITLE
Add continuous colour palettes to grattan_(colour|fill)_manual

### PR DESCRIPTION
**Pull request by wfmackey**
Generate continuous colour palettes with `grattan_(colour|fill)_manual(discrete = FALSE). 
Choose palette with `palette = "full"`, `palette = "full_f"`, `palette = "light"`, `palette = "dark"`, `palette = "diverging"`, `palette = "grey"`. 
Added faded colours with suffix `_f`, eg `grattan_yellow_f`. 

Added tests to appease code coverage checks.

### CODE REVIEW

**Comment by wfmackey** [comment]
omg codecov

**Comment by MattCowgill** [comment]
don't worry about such a small fall in coverage

**Comment by MattCowgill** [comment]
PR merged - pls delete the branch if you're done with it @wfmackey

**Comment by wfmackey** [comment]
Updating the vignettes on this branch. Will PR and delete after that.

**Pull request merged**
